services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4008:4008"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4008"]
    volumes:
      - ./backend/uploads:/home/user/app/uploads
      - ./backend/yolov8n.pt:/home/user/app/yolov8n.pt
    environment:
      - FRONTEND_URL=http://localhost:3008

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3008:80"
    depends_on:
      - backend
